{
 "title": "Dashboard Post",
 "description": "Dashboard for instrumented applications (NodeJS, Spring Boot, Quarkus)",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Logs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate({container_name=~\"/service-a|/service-b|/service-c|/service-d\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "Uso de CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_system_seconds_total{job=\"service-a\"}[5m])",
     "legendFormat": "servicio-a"
    },
    {
     "expr": "system_cpu_usage{job=\"service-b\"}",
     "legendFormat": "servicio-b"
    },
    {
     "expr": "system_cpu_usage{job=\"service-c\"}",
     "legendFormat": "servicio-c"
    },
    {
     "expr": "system_cpu_usage{job=\"service-d\"}",
     "legendFormat": "servicio-d"
    }
   ]
  },
  {
   "title": "Trazas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true
  },
  {
   "title": "Trazas con error",
   "type": "table",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{container_name=~\".*service-.*\"} |= `error`"
    }
   ]
  },
  {
   "title": "Trazas Servicio A",
   "type": "table",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 9 },
   "targets": [
    {
     "expr": "{container_name=~\"/service-b\"} != `error` |= `traceId`"
    }
   ]
  },
  {
   "title": "Métricas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true
  },
  {
   "title": "Numero de peticiones total",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{job=\"service-b\", uri=\"/b-service\"}[2m])",
     "legendFormat": "{{method}} - {{uri}} - {{status}}"
    },
    {
     "expr": "rate(http_server_requests_seconds_count{job=\"service-c\", uri=\"/c-service\"}[2m])",
     "legendFormat": "{{method}} - {{uri}} - {{status}}"
    },
    {
     "expr": "rate(http_server_requests_seconds_count{job=\"service-d\", uri=\"/d-service\"}[2m])",
     "legendFormat": "{{method}} - {{uri}} - {{status}}"
    },
    {
     "expr": "rate(http_request_duration_seconds_count{job=\"service-a\", path=\"/\"}[2m])",
     "legendFormat": "{{method}} - {{path}} - {{status_code}}"
    }
   ]
  },
  {
   "title": "Duración media de peticiones",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{job=\"service-a\", path=\"/\"}[4m]) / rate(http_request_duration_seconds_count{job=\"service-a\", path=\"/\"}[4m])",
     "legendFormat": "{{method}} - {{path}} - {{status_code}}"
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{job=\"service-b\", uri=\"/b-service\"}[4m]) / rate(http_server_requests_seconds_count{job=\"service-b\", uri=\"/b-service\"}[4m])",
     "legendFormat": "{{method}} - {{uri}} - {{status}}"
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{job=\"service-d\", uri=\"/d-service\"}[4m]) / rate(http_server_requests_seconds_count{job=\"service-d\", uri=\"/d-service\"}[4m])",
     "legendFormat": "{{method}} - {{uri}} - {{status}}"
    }
   ]
  },
  {
   "title": "Peticiones API Rest Erróneas",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{job=\"service-a\",method=\"POST\",path=\"/\",status_code!~\"2..\"}[2m]))",
     "legendFormat": "service-a"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"service-b\",method=\"POST\",uri=\"/b-service\",status!~\"2..\"}[2m]))",
     "legendFormat": "service-b"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"service-d\",method=\"POST\",uri=\"/d-service\",status!~\"2..\"}[2m]))",
     "legendFormat": "service-d"
    }
   ]
  }
 ]
}